config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Home path -- index
  root to: 'home#index'

  # Static page
  get '/index',     to: 'home#index'
  get '/sitemap',   to: 'home#sitemap'
  get '/cgu',       to: 'home#cgu'
  get '/privacy',   to: 'home#privacy'
  get '/contact',   to: 'home#contact'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Primary controller to application
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = :fr # use_language
  end

  private

  def use_language
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first || I18n.default_locale
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Signle controller
class HomeController < ApplicationController
  # GET /index
  def index; end

  # GET /sitemap
  def sitemap; end

  # GET /cgu
  def cgu; end

  # GET /contact
  def contact; end

  # GET /privacy
  def privacy; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Generic method helper
module ApplicationHelper
  def title_page
    tag.div class: 'columns' do
      tag.div class: 'column col-12' do
        tag.h1 { title }
      end
    end
  end

  def title
    I18n.t("titles.#{controller_name}.#{action_name}")
  end

  def images_count(path)
    1..array_images(path).count
  end

  def image_carousel(path, indx)
    "#{path}/#{array_images(path)[indx - 1]}"
  end

  private

  def path_images(path)
    Dir[Rails.root.join('app', 'assets', 'images', path)].join('/')
  end

  def array_images(path)
    Dir.entries(path_images(path)) - ['..', '.']
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Helper for home pages
module HomeHelper
  def timeline(year, month, last: false)
    tag.div id: id_timeline(year, month), class: 'timeline-item' do
      capture do
        concat timeline_left(year, month, last)
        concat timeline_right(year, month)
      end
    end
  end

  private

  def id_timeline(year, month)
    "timeline-#{year}-#{month}"
  end

  def timeline_left(year, month, last)
    tag.div class: 'timeline-left' do
      tag.a class: timeline_icon(last), href: "##{id_timeline(year, month)}" do
        tag.i class: 'icon icon-check' unless last
      end
    end
  end

  def timeline_icon(last)
    if last
      'timeline-icon'
    else
      'timeline-icon icon-lg'
    end
  end

  def timeline_right(year, month)
    tag.div class: 'timeline-content' do
      capture do
        concat timeline_right_title(year, month)
        concat timeline_right_desc(year, month)
      end
    end
  end

  def timeline_right_title(year, month)
    tag.div class: 'title' do
      tag.h3 I18n.t("timeline.#{year}.#{month}.title")
    end
  end

  def timeline_right_desc(year, month)
    tag.div class: 'content' do
      tag.p I18n.t("timeline.#{year}.#{month}.desc")
    end
  end
end

app/views/home/cgu.html.haml
%h1 Home#cgu
%p Find me in app/views/home/cgu.html.haml

app/views/home/contact.html.haml
%h1 Home#contact
%p Find me in app/views/home/contact.html.haml

app/views/home/index.html.haml
#index
  .columns
    .column.col-md-12.flex-centered
      %h1
        = I18n.t('app.title')

  .columns
    .column.col-md-12.flex-centered
      #index-carousel
        - locals = { folder: 'index' }
        = render partial: 'shared/carousel', locals: locals
    .column.col-md-12.flex-centered
      .timeline
        %h2 Timeline
        = timeline('_2022', 'january', last: true)
        = timeline('_2017', 'december')

  .divider

  .columns
    .column.col-md-12.flex-centered
      %h1
        = I18n.t('index.title')

  .columns
    .column.col-md-12.flex-centered
      %p
        = I18n.t('index.describ')

  = render partial: 'shared/download'

app/views/home/privacy.html.haml
%h1
  Politique de confidentialité

%p
  OpenBD est une application open source disponible sur iOS et Android. Ce
  service vous est fourni gratuitement par Jeremy Vaillant et est destiné à
  être utilisé tel quel.

%p
  Le but de cette page est d’informer les utilisateurs sur notre politique e
  n matière de collecte, d’utilisation et de divulgation d’informations
  personnelles lorsque quelqu’un utilise le service.

%p
  Si vous choisissez d’utiliser OpenBD, vous acceptez la collecte et
  l’utilisation d’informations dans le cadre de cette politique. Les
  informations personnelles collectées sont utilisées pour fournir et améliorer
  le service. Ces informations ne seront ni utilisées, ni partagées avec qui que
  ce soit, sauf dans les cas décrits dans la présente politique de
  confidentialité.

%h2
  Journaux d’accès (logs)

%p
  Afin de nous assurer du bon fonctionnement de OpenBD, nous collectons les
  données suivantes lors de l’utilisation du service :
  %ul
    %li
      l’adresse IP de l’appareil
    %li
      l’heure et la date de l’utilisation

%p
  Ces informations ne sont pas utilisées à des fins commerciales et ne sont
  pas conservées plus de quatre semaines.

%h1
  Collecte et utilisation d’informations

%p
  Mis à part les informations enregistrées dans les journeaux d’accès
  mentionnées plus haut, OpenBD ne collecte pas d’informations personnelles
  sur ses serveurs.

%h1
  Tierces parties

%p
  OpenBD ne partage pas d’informations personnelles avec des tierces parties.
  Nous utilisons les données des services suivants afin de fournir notre service :
  %ul
    %li
      l’API api.bnf.fr pour la recherche d'oeuvre ;

%p
  Ces sources de données sont contactées à chaque fois que vous utilisez OpenBD.
  Cependant, ces requêtes sont effectuées depuis nos serveurs, anonymisant
  ainsi la personne à l’origine de la demande.

%h1
  Sécurité

%p
  Nous apprécions la confiance que vous portez lors de l’utilisation de
  OpenBD ; nous nous efforçons donc d’utiliser des moyens de protection
  convenables. Mais rappelez-vous qu’aucune méthode de transmission sur
  Internet ou de stockage électronique n’est sécurisée et fiable à 100%, et
  nous ne pouvons en garantir la sécurité absolue.

%h1
  Liens vers des sites externes

%p
  Ce service peut contenir des liens vers d’autres sites web. Notez que ces
  sites externes ne sont pas exploités par OpenBD : par conséquent, il est
  conseillé d’également consulter leur politique de confidentialité. Nous
  n’avons aucun contrôle sur le contenu, les politiques de confidentialité et
  les pratiques de tout site ou service tiers, et n’assume aucune
  responsabilité à leur égard.

%h1
  Hébergement

%p
  OpenBD est hébergé sur les serveurs Contabo à Munich.

%h1
  Mises à jour de la politique de confidentialité

%p
  Cette politique de confidentialité peut être mise à jour de temps à autre. Les
  modifications sont publiées sur cette page et entrent en vigueur immédiatement
  après leur publication.

%h1
  Contact

%p
  En cas de questions ou de suggestions à propos de la politique
  de confidentialité, n’hésitez pas à nous contacter.

app/views/home/sitemap.html.haml
.columns
  .column.col-12
    %ul
      %li= link_to t('sitemap.index'), root_path
      -#%li= link_to t('sitemap.about'), about_path
      %li= link_to t('sitemap.sitemap'), sitemap_path
      %li= link_to t('sitemap.cgu'), cgu_path
      -#%li= link_to t('sitemap.contact'), contact_path
      %li= link_to t('sitemap.privacy'), privacy_path

app/views/layouts/application.html.haml
!!!
%html{ lang: I18n.default_locale }
  %head
    %meta{ charset: 'utf-8' }
    %meta{ content: 'ie=edge', 'http-equiv': 'x-ua-compatible' }
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }
    %title
      = t('app.title')
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body
    = render 'shared/top'
    .container
      = yield
  = render partial: 'shared/footer'

app/views/shared/_carousel.html.haml
- range = images_count(folder)

.carousel
  - range.each_with_index do |_, index|
    %input.carousel-locator{ name: 'carousel-radio',
                             id: "slide-#{index}",
                             type: 'radio',
                             checked: index.zero? ? true : false,
                             hidden: true }
  .carousel-container
    - range.each_with_index do |_, index|
      %figure.carousel-item
        = image_tag image_carousel(folder, index), class: 'img-responsive'
    .carousel-nav
      - range.each_with_index do |_, index|
        %label.nav-item.text-hide.c-hand{ for: "slide-#{index}" }
          = index

app/views/shared/_download.html.haml
.columns#dl
  .column.min-height.col-md-12.flex-centered
    = link_to I18n.t('index.download.play-store.link'), class: 'btn-primary btn btn-lg', id: 'dl-play-store' do
      = image_tag 'play-store-download.png', class: 'icon', height: 18, width: 60
      = I18n.t('index.download.play-store.text')
  .divider-vert.hide-md{ 'data-content': 'or' }
  .column.min-height.col-md-12.flex-centered
    = link_to I18n.t('index.download.fdroid.link'), class: 'btn-primary btn btn-lg', id: 'dl-fdroid' do
      = image_tag 'f-droid-download.png', class: 'icon', height: 18, width: 60
      = I18n.t('index.download.fdroid.text')

app/views/shared/_footer.html.haml
%footer
  .columns
    .col-sm-12.col-4
      %ul.menu
        %li.divider{ 'data-content': I18n.t('footer.sources.title') }
        %li.menu-item
          = link_to(I18n.t('footer.sources.api'), 'https://framagit.org/GRem/open-bd')
        %li.menu-item
          = link_to(I18n.t('footer.sources.android'), 'https://framagit.org/GRem/open-bd-android')
        %li.menu-item
          = link_to(I18n.t('footer.sources.web'), 'https://framagit.org/GRem/open-bd-site')
    .col-sm-12.col-4
      %ul.menu
        %li.divider{ 'data-content': I18n.t('footer.navigations.title') }
        %li.menu-item
          = link_to(I18n.t('footer.navigations.sitemap'), sitemap_path)
        -#%li.menu-item
          = link_to(I18n.t('footer.navigations.about'), about_path)
        -#%li.menu-item
          = link_to(I18n.t('footer.navigations.contact'), contact_path)
        %li.menu-item
          = link_to(I18n.t('footer.navigations.eula'), cgu_path)
        %li.menu-item
          = link_to(I18n.t('footer.navigations.privacy'), privacy_path)
    .col-sm-12.col-4
      %ul.menu
        %li.divider{ 'data-content': I18n.t('footer.thanks.title') }
        %li.menu-item
          = link_to(I18n.t('footer.thanks.framasoft'), 'https://framasoft.org')
        %li.menu-item
          = link_to 'https://liberapay.com/DevCrea/donate', id: 'liberapay' do
            %svg{ viewBox: '0 0 80 80', height: 16, width: 16 }
              %g{ fill: '#1a171b', transform: 'translate(-78.37-208.06)' }
                %path{ d: 'm104.28 271.1c-3.571 0-6.373-.466-8.41-1.396-2.037-.93-3.495-2.199-4.375-3.809-.88-1.609-1.308-3.457-1.282-5.544.025-2.086.313-4.311.868-6.675l9.579-40.05 11.69-1.81-10.484 43.44c-.202.905-.314 1.735-.339 2.489-.026.754.113 1.421.415 1.999.302.579.817 1.044 1.546 1.395.729.353 1.747.579 3.055.679l-2.263 9.278' }
                %path{ d: 'm146.52 246.14c0 3.671-.604 7.03-1.811 10.07-1.207 3.043-2.879 5.669-5.01 7.881-2.138 2.213-4.702 3.935-7.693 5.167-2.992 1.231-6.248 1.848-9.767 1.848-1.71 0-3.42-.151-5.129-.453l-3.394 13.651h-11.162l12.52-52.19c2.01-.603 4.311-1.143 6.901-1.622 2.589-.477 5.393-.716 8.41-.716 2.815 0 5.242.428 7.278 1.282 2.037.855 3.708 2.024 5.02 3.507 1.307 1.484 2.274 3.219 2.904 5.205.627 1.987.942 4.11.942 6.373m-27.378 15.461c.854.202 1.91.302 3.167.302 1.961 0 3.746-.364 5.355-1.094 1.609-.728 2.979-1.747 4.111-3.055 1.131-1.307 2.01-2.877 2.64-4.714.628-1.835.943-3.858.943-6.071 0-2.161-.479-3.998-1.433-5.506-.956-1.508-2.615-2.263-4.978-2.263-1.61 0-3.118.151-4.525.453l-5.28 21.948' }
            %span= t('footer.thanks.don')

app/views/shared/_top.html.haml
%header.navbar
  %section.navbar-section
    .btn
      = link_to root_path do
        = image_tag 'favicon.png', class: 'icon', size: 20
        = I18n.t('app.title')
-#
  %section.navbar-section
    %h2= title
    = link_to users_registrations_new_path, class: 'btn btn-success' do
      %i.icon.icon-people
      = t('app.signup')